In [91]:
%display latex
import code as pc
import numpy as np
Partitions.options.latex='list'

# Given a partition 
def to_fock(partition):
    return vector([(x-(i+1)) for i, x in enumerate(partition)])

def to_partition(fock_vector):
    return Partition([(x+(i+1)) for i, x in enumerate(fock_vector)])


# Take a list, sort it into weakly decreasing order using only
# transpositions, and count the number of transpositions needed.
def num_swaps(L):
    Lp = copy(L)
    swapcount = 0
    for j in range(len(Lp)):
        for i in range(1, len(Lp)-j):
            if Lp[i-1] > Lp[i]:
                swapcount += 1
                Lp[i-1], Lp[i] = Lp[i], Lp[i-1]
    sign = -1 if swapcount % 2 == 0 else 1
    Lpp = list(Lp)
    Lpp.reverse()
    return vector(Lpp), sign

def do_mult(l):
    (v, s) = num_swaps(l)
    return(s*v)

In [92]:
def alpha(k, v_lambda):
    
    # Length of fock vector
    n = len(v_lambda)
    
    # Stack n copies of v_lambda up as the rows of an nxn matrix
    V = Matrix([ v_lambda for i in range(n) ])
    
    # A scalar matrix for k
    kI = identity_matrix(n) * k
    
    # Subtract k off of the diagonal
    M = V - kI
    
    # Sorted vectors, with the (signs of the) number of transpositions
    # Throw away vectors with repeated entries, since these
    # wedge to zero.
    L = [do_mult(R) for R in M.rows() if len(R) == len(set(R))]
    return(sum(L))

def alphap(k, v_lambda):
    
    # Length of fock vector
    n = len(v_lambda)
    
    # Stack n copies of v_lambda up as the rows of an nxn matrix
    V = Matrix([ v_lambda for i in range(n) ])
    
    # A scalar matrix for k
    kI = identity_matrix(n) * k
    
    # Subtract k off of the diagonal
    M = V - kI
    
    # Sorted vectors, with the (signs of the) number of transpositions
    # Throw away vectors with repeated entries, since these
    # wedge to zero.
    L = [num_swaps(R) for R in M.rows() if len(R) == len(set(R))]
    
    match_out1 = [ l[0] for l in L ]
    match_out2 = [ l[1] for l in L ]
    return([ match_out1, match_out2 ])

In [12]:
l = [3,1,1]
v_l = to_fock(l)
show(l)

[3, 1, 1]

In [13]:
A = alpha(1, v_l)
A

(3, -2, -5)

In [121]:
parts = Partitions(5).list()
n = 5
m = len(parts)

M = identity_matrix(ZZ, m)

def pad_to_n(v):
    vp = (list(v) + m * [0])[:m]
    return(vector(vp))

for i,p in enumerate(parts):
    a = pad_to_n(to_fock(p))
    M.set_column(i, a)
    show(p, "_____", a)
M

[5] '_____' (4, 0, 0, 0, 0, 0, 0)

[4, 1] '_____' (3, -1, 0, 0, 0, 0, 0)

[3, 2] '_____' (2, 0, 0, 0, 0, 0, 0)

[3, 1, 1] '_____' (2, -1, -2, 0, 0, 0, 0)

[2, 2, 1] '_____' (1, 0, -2, 0, 0, 0, 0)

[2, 1, 1, 1] '_____' (1, -1, -2, -3, 0, 0, 0)

[1, 1, 1, 1, 1] '_____' (0, -1, -2, -3, -4, 0, 0)

[ 4  3  2  2  1  1  0]
[ 0 -1  0 -1  0 -1 -1]
[ 0  0  0 -2 -2 -2 -2]
[ 0  0  0  0  0 -3 -3]
[ 0  0  0  0  0  0 -4]
[ 0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0]

In [75]:
len(parts)

7

In [81]:
out = alpha(-2, alpha(-3, v_l))
show(out)
show(pad_to_n(out))

(-5, 0, 3)

(-5, 0, 3, 0, 0, 0, 0)

In [84]:
v = pad_to_n(out)
w = M.T*v
w

(-20, -15, -10, -16, -11, -11, -6)

In [86]:
w

(-20, -15, -10, -16, -11, -11, -6)

In [47]:
p.size()

5

In [48]:
n = p.size()
ZZ^n

Ambient free module of rank 5 over the principal ideal domain Integer Ring

In [88]:
lll = Partition([3,1,1])
to_fock(lll)

(2, -1, -2)

In [94]:
alphap(-3, to_fock(lll))

[[(5, -1, -2), (2, 1, -1)], [1, -1]]

In [144]:
w1 = alpha(-3, to_fock(lll))
w = alpha(-2, w1)
w

(-5, 0, 3)

In [145]:
wp = padout(w)
wp

(-5, 0, 3, -4, -5, -6, -7)

In [148]:
M*wp

(-33, 27, 50, 83, 113, 144, 168)

In [108]:
to_fock(pad_to_n(wp))

(2, -4, -4, -4, -5, -6, -7)

In [135]:
def padout(partition):
    v0 = zero_vector(7)
    for i in range(7):
        if i < len(partition):
            v0[i] = partition[i]
        else:
            v0[i] = -i-1
    return(v0)

In [136]:
padout([2,-1,-2])

(2, -1, -2, -4, -5, -6, -7)

In [138]:
M = identity_matrix(ZZ, 7)
parts = Partitions(5)
for i,p in enumerate(parts):
    a = padout(to_fock(p))
    show(a)
    M.set_column(i, a)
M

(4, -2, -3, -4, -5, -6, -7)

(3, -1, -3, -4, -5, -6, -7)

(2, 0, -3, -4, -5, -6, -7)

(2, -1, -2, -4, -5, -6, -7)

(1, 0, -2, -4, -5, -6, -7)

(1, -1, -2, -3, -5, -6, -7)

(0, -1, -2, -3, -4, -6, -7)

[ 4  3  2  2  1  1  0]
[-2 -1  0 -1  0 -1 -1]
[-3 -3 -3 -2 -2 -2 -2]
[-4 -4 -4 -4 -4 -3 -3]
[-5 -5 -5 -5 -5 -5 -4]
[-6 -6 -6 -6 -6 -6 -6]
[-7 -7 -7 -7 -7 -7 -7]

In [139]:
M.inverse()

ZeroDivisionError: matrix must be nonsingular