# References

[Lazy Power Series](http://doc.sagemath.org/html/en/reference/combinat/sage/combinat/tutorial.html)

[Lazy Laurent Series](http://doc.sagemath.org/html/en/reference/power_series/sage/rings/lazy_laurent_series.html)

[Integer Partitions](http://doc.sagemath.org/html/en/reference/combinat/sage/combinat/partition.html)


In [157]:
%display latex
import code as pc
import numpy as np
Partitions.options.latex='list'

In [158]:
part1 = [3,1,1]
fock_vec = [2, -1, -2]

In [160]:
def to_fock(partition):
    return vector([(x-(i+1)) for i, x in enumerate(part1)])

def to_partition(fock_vector):
    return Partition([(x+(i+1)) for i, x in enumerate(fock_vector)])

In [161]:
print(pc.fock(part1))
print(to_fock(part1))

[ 2 -1 -2]
(2, -1, -2)


In [162]:
print(pc.partition(fock_vec))
print(to_partition(fock_vec))

[3 1 1]
[3, 1, 1]


In [163]:
p = to_partition(fock_vec)
print(p)
print(p.ferrers_diagram())

[3, 1, 1]
***
*
*


In [164]:
Tableaux.options.ascii_art = "table"
print(p.hook_length(0, 0))
hlens = p.hook_lengths()
ascii_art(Tableau(hlens))

5


+---+---+---+
| 5 | 2 | 1 |
+---+---+---+
| 2 |
+---+
| 1 |
+---+

In [165]:
def alpha_k(v_lambda, k):
    M = Matrix([ v for i in range(v.length()) ])
    Av = M + identity_matrix(v.length()) * k
    return sum(Av)

In [166]:
v = to_fock(part1)
alpha_k(v, 2)

(8, -1, -4)

In [168]:
# Sum(A) for a matrix sums columns.
M = Matrix(QQ, 3, 
           [1,0,0, 
            2,0,1, 
            0,7,0

           ])
show(M)
sum(M)

[1 0 0]
[2 0 1]
[0 7 0]

(3, 7, 1)

In [169]:
fock = v
n = 1

M = Matrix([ fock for i in range(fock.length()) ])
Ik = identity_matrix(fock.length()) * n
Av = M - Ik
show(M, "+", Ik, "=", Av)

[ 2 -1 -2]
[ 2 -1 -2]
[ 2 -1 -2] '+' [1 0 0]
[0 1 0]
[0 0 1] '=' [ 1 -1 -2]
[ 2 -2 -2]
[ 2 -1 -3]

In [ ]:
Partitions.options(display="list")
for a in Partitions(5).list(): print(a)

In [172]:
Ms = pc.lowering1(v, 1)
show(v)
Ms

(2, -1, -2)

[array([[ 1, -1, -2],
        [ 2, -1, -3]]), [1, 1]]

In [176]:
fock = v
n = 1
s = len(fock)
# Stack vectors into square matrix
start = np.array([fock,]*s)
start

array([[ 2, -1, -2],
       [ 2, -1, -2],
       [ 2, -1, -2]])

In [177]:
for i in range(s):
    start[i][i]=start[i][i]-n
start

array([[ 1, -1, -2],
       [ 2, -2, -2],
       [ 2, -1, -3]])

In [178]:
# Pick rows where every entry is > -(1+s)
print(-1-s)
goodrows = start[np.all(start>-1-s, axis=1)]
goodrows

-4


array([[ 1, -1, -2],
       [ 2, -2, -2],
       [ 2, -1, -3]])

![](https://i.stack.imgur.com/h1alT.jpg)

In [179]:
betterrows = np.fliplr(np.sort(goodrows,axis=1))
betterrows

array([[ 1, -1, -2],
       [ 2, -2, -2],
       [ 2, -1, -3]])

In [ ]:
# Fliplr: puts columns in reverse order.
A = np.diag([1,2,3])
show(A)
B = np.fliplr(A)
show(B)

In [180]:
counterlist = []
norepeatlist = []
nottoobig = []
accuracy = 70

In [181]:
t=len(betterrows)
list(range(t))

[0, 1, 2]

In [182]:
goodrows

array([[ 1, -1, -2],
       [ 2, -2, -2],
       [ 2, -1, -3]])

In [186]:
i = 0
counter = -1
givenrow1 = goodrows[i]
givenrow1

array([ 1, -1, -2])

In [187]:
if sum(pc.partition(givenrow1))>accuracy:
    print("break")
givenrow2 = betterrows[i]
norepeats = True
givenrow2

array([ 1, -1, -2])

In [188]:
for j in range(s):
    if givenrow1[j]!=givenrow2[j]:
        counter = counter + 1
    if j<s-1:
        if givenrow2[j]==givenrow2[j+1]:
            norepeats = False
            break
show(counter)
show(norepeats)

-1

True

In [189]:
if norepeats==True:
    norepeatlist.append(i)
norepeatlist

[0]

In [190]:
counterlist.append(max(0,counter))
counterlist

[0]

In [192]:
counterlist = []
norepeatlist = []
nottoobig = []
t=len(betterrows)
for i in range(t):
    counter = -1
    givenrow1 = goodrows[i]
    if sum(pc.partition(givenrow1))>accuracy:
#            print('Warning: Set accuracy higher.')
        print("break")
    givenrow2 = betterrows[i]
    norepeats = True
    for j in range(s):
        if givenrow1[j]!=givenrow2[j]:
            counter = counter + 1
        if j<s-1:
            if givenrow2[j]==givenrow2[j+1]:
                norepeats = False
                break
    if norepeats==True:
        norepeatlist.append(i)
    counterlist.append(max(0,counter))

In [193]:
counterlist

[0, 0, 0]

In [194]:
norepeatlist

[0, 2]

# Swap Distance / Transposition Distance

Note: an NP-Hard problem [CS Paper from 2010](https://arxiv.org/abs/1011.1157)

Let $v, w$ be vectors in $\mathbb{Z}^n$ such that the entries of $v$ are in weakly decreasing order, and the entries of $w$ are some permutation of the entries of $v$.

Define $d(v, w)$ to be the number of transpositions needed to transform $v$ to $w$.

## Algorithm 1 (Brute Force Count)
Perform a bubble sort and count the number of transpositions. Scales like $O(n^2)$ in the length of the vector.

## Other Possibilities

**Algorithm 2**
Define a map
$$
S: \mathbb{Z} \to \mathbb{R}^{2n} \\
v \mapsto S(v)_{ij} = \begin{cases}1 & v_i < v_j \\ 0 & \text{else} \end{cases}
$$

Then (claim) $$d(v, w) = \| S(v) - S(w) \|_{2}^2.$$

[Reference: computing swap distances via Euclidean embedding](http://dimacs.rutgers.edu/~graham/pubs/slides/dmsa.pdf)

*Seems to be off by 1 sometimes..*.

**Matrix Rank:**
Compute the rank of an associated permutation matrix.
[Reference](https://math.berkeley.edu/~mhegde/other_math/permutation_distance.pdf)

Conjecture: Let $\sigma \in S^n$ be a permutation and $P(\sigma) \in \mathbb{Z}^{n^2}$ be its associated permutation matrix. Let $d(\sigma)$ be the number of transpositions that reduce $\sigma$ to the identity. Then

$$d(\sigma) = \mathrm{rank}(I_n - P(\sigma)).$$

Problem: how to convert an arbitrary vector to a permutation..?

**Direct Formula:**
Somehow convert vector of length $n$ to a cycle $\sigma \in S_n$. Then $d(\sigma, \mathrm{id}) = n - c(\sigma)$, the number of cycles in a disjoint cycle decomposition.

Problem: how to convert an arbitrary vector to a permutation..?


In [132]:
v = vector([1,2,1])
v

(1, 2, 1)

In [135]:
len(v) == len(set(v))

False

In [146]:
M = Matrix(QQ, 3, [1,1,1, 1,1,1, 1,2,3])
M

[1 1 1]
[1 1 1]
[1 2 3]

In [149]:
[R for R in M.rows() if len(R) == len(set(R))]

[(1, 2, 3)]

In [150]:
fock

NameError: name 'fock' is not defined

[ 2 -1 -2]
[ 2 -1 -2]
[ 2 -1 -2] '+' [1 0 0]
[0 1 0]
[0 0 1] '=' [ 3 -1 -2]
[ 2  0 -2]
[ 2 -1 -1]